server:
   port: 8760

eureka:
   instance:
       hostname: localhost
   client:
       registerWithEureka: false
       fetchRegistry: false

spring:
  application:
    name: eureka-server
  cloud:
    config:
      label: master
      profile: dev
      url: http://localhost:8888/
      enabled: false