server:
   port: 8760

eureka:
   instance:
       hostname: localhost
   client:
       registerWithEureka: false
       fetchRegistry: false

spring:
  cloud:
    config:
      enabled: true

profiles:
  dev